# Generated by Django 5.0.6 on 2024-06-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appitself', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='point',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
