# Generated by Django 5.0.6 on 2024-06-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appitself', '0002_alter_point_latitude_alter_point_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='street',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
